### ISSUE TITLE
uhorn glyphs should overlap

### ISSUE THREAD

**Issue by m4rc1e** [cyrealtype/Inconsolata#11]
![screen shot 2017-06-22 at 11 56 20](https://user-images.githubusercontent.com/7525512/27430824-f997dca6-5741-11e7-99c4-c69653e5433e.png)

![screen shot 2017-06-22 at 11 57 50](https://user-images.githubusercontent.com/7525512/27430843-095c7b38-5742-11e7-9aaf-9474941ef35a.png)

**Comment by alexeiva** [comment]
I've a déjà vu that I already fixed this. Probably in another font. This is a popular problem. Noted. Thanks.
