### ISSUE TITLE
En Dash issue

### ISSUE THREAD

**Issue by davelab6** [cyrealtype/Inconsolata#15]
https://github.com/google/fonts/issues/1373

**Comment by alexeiva** [comment]
hyphen, endash, emdash:

<img width="621" alt="screen shot 2017-12-11 at 9 06 11 pm" src="https://user-images.githubusercontent.com/16634089/33843616-4f1f58a0-deb7-11e7-9449-791a25fc2629.png">
<img width="601" alt="screen shot 2017-12-11 at 9 06 16 pm" src="https://user-images.githubusercontent.com/16634089/33843617-4f41b418-deb7-11e7-801a-371924953934.png">

**Comment by tamsky** [comment]
Thank you very much!
