### ISSUE TITLE
Combining marks

### ISSUE THREAD

**Issue by m4rc1e** [cyrealtype/Inconsolata#2]
Hey Alexei,

The combining marks should be [0 width](http://www.fileformat.info/info/unicode/char/0300/index.htm)

**Roboto**
![screen shot 2016-09-22 at 11 17 28](https://cloud.githubusercontent.com/assets/7525512/18742749/2f36d2d0-80b6-11e6-8a84-89a55ed8781f.png)

**Inconsolata**
![screen shot 2016-09-22 at 11 18 26](https://cloud.githubusercontent.com/assets/7525512/18742779/4dbbd976-80b6-11e6-89ec-c7d7a5703e10.png)

**Comment by alexeiva** [comment]
This is how all my combining accents where built. I would need to update all my fonts.

**Comment by m4rc1e** [comment]
Ooosh @davelab6 what do you think about this?

Apologies I am quite militant about specs. I guess this may not be such a huge issue.

**Comment by alexeiva** [comment]
We should ask/search on glyphs forums. It is more convenient to have ~50 sidebearings during the drawing / anchor placement process. 

My thought are — since there are anchors, does it eliminate the need for zero width glyphs?

I checked some system fonts:
Arial has zero width comb marks, and no anchors. 

Dejavu has zero width and also an anchor. 

![screen shot 2016-09-22 at 12 45 41](https://cloud.githubusercontent.com/assets/16634089/18745478/91be8c48-80c2-11e6-8c3e-e1889ee05651.png)

**Comment by m4rc1e** [comment]
These glyphs fall under a category called [Mark, Nonspacing](http://www.fileformat.info/info/unicode/category/Mn/list.htm)

I'm guessing people put them on -50 because this would shift it over a base character, if a comp glyph didn't exist. Kinda like a safety not. Don't quote me on this, I could be wrong.

I've now written a check for my Glyphsapp QA tool to test this. 
![screen shot 2016-09-22 at 12 55 43](https://cloud.githubusercontent.com/assets/7525512/18745788/eb7f70de-80c3-11e6-81df-15cfac025a0c.png)

**Comment by alexeiva** [comment]
Best would be to fix this via your script. 

What do you think about mekkablue's preflight font script — it's naming check is good. 

Another question is vendorID — in case of a missing ID, and if the author isn't registered on mircosoft's website, what value should we use? Perhaps we can register a new ID for googlefonts?

**Comment by m4rc1e** [comment]
Its difficult to implement a fix for this as an auto script.

What if someone has used the combmark as a composite?

If I set the metrics to 0 or a -50 offset, it could wreck their component glyphs.

Preflight font does not check this. However, it is a good tool.


I'm happy to write a script which will check if these comb glyphs are used as composites. If they are'nt, then they can be moved ;).

Give me 30 mins please.

Cheers,
Marc

**Comment by alexeiva** [comment]
Boom!

<img width="463" alt="screen shot 2016-09-22 at 13 39 03" src="https://cloud.githubusercontent.com/assets/16634089/18746837/02d860be-80ca-11e6-97d7-8e47b6f84c2b.png">

I just examined the exported Inconsolata TFFs:

![screen shot 2016-09-22 at 13 38 59](https://cloud.githubusercontent.com/assets/16634089/18746843/082b18a4-80ca-11e6-96ad-5a6357b25b4b.png)

**Comment by m4rc1e** [comment]
I like, issue close ;)

**Comment by m4rc1e** [comment]
Right, I also removed the test for this from my QA.
