### ISSUE TITLE
Accent Positioning

### ISSUE THREAD

**Issue by m4rc1e** [cyrealtype/Inconsolata#3]
Hey Alexei,

Some of the diacritic positions broke after commit 41c7bcb.

Please check the differences between the two. I think the problem may be the anchors, however this is also related to #2 

**latest commit**
![screen shot 2016-09-22 at 11 09 19](https://cloud.githubusercontent.com/assets/7525512/18742896/d4ea4586-80b6-11e6-8814-c878b55bc392.png)

**41c7bcb**
![screen shot 2016-09-22 at 11 22 43](https://cloud.githubusercontent.com/assets/7525512/18742918/e7078fee-80b6-11e6-908c-16b503534190.png)

Cheers,
Marc

**Comment by alexeiva** [comment]
Marc, thanks for digging deep into this. 

The anchors were misplaced in commit e6a7b84. I relate this to a glyphs bug, I have been struggling with that week. I couldn't export TTFs, and Glyphs kept crashing. 

The current Glyphs version fixes it. 

Let me fix this in the new sources, and then we should sync the sources again. 

If you have done any changes to this point — can you merge them into my sources?









<img width="320" alt="screen shot 2016-09-22 at 14 06 27" src="https://cloud.githubusercontent.com/assets/16634089/18747487/e4969374-80cd-11e6-82af-1154f30ade67.png">

**Comment by m4rc1e** [comment]
Hey Alexei,

I've done no changes ;)

I'm QAing everything before I master ;)
