### ISSUE TITLE
Wrong alignment in Firefox and Chrome

### ISSUE THREAD

**Issue by chi-plus-plus** [cyrealtype/Inconsolata#65]
I'm using your font in my Web site, but the alignment on multiple columns like:

#define  STR_RGB    "colore RGB"
#define  STR_RED    "rosso"
#define  STR_GREEN  "verde"
#define  STR_BLUE   "blu"

is displayed correctyl only in Safari:

<img width="557" alt="Screenshot 2020-12-26 at 11 47 40" src="https://user-images.githubusercontent.com/61247652/103150056-6452f680-4770-11eb-8c3d-aecfed19bc24.png">

in Chrome and in Firefox it is displayed as if it was a variable width font:

![Screenshot 2020-12-26 at 11 48 01](https://user-images.githubusercontent.com/61247652/103150065-703eb880-4770-11eb-92ce-0163bea68e33.png)

It's, a font issue, a browser issue (more likely) or am I doing something wrong?
Thank you,
C:

**Comment by itepechi** [comment]
I noticed that you have accidentally disabled Inconsolata for some characters. (` `, `!`, `"`, `#`, `$` and characters after `Ā`)

Removing `unicode-range: U+0025-00FF;` from `stili.css` will fix the problem.

**Comment by chi-plus-plus** [comment]
Thank you! I don't know why I've added that line.
It's correct now.
Grazie! If you ever will be in Rome, I'll be happy to offer you a Campari and the best Carbonara in town.

C:

**Comment by itepechi** [comment]
I'm happy to hear that; I wish to visit there someday!

I checked the website again, everything looks good. I think this issue can be closed now.

**Comment by chi-plus-plus** [comment]
Yes. Thank you again.
C:
