### ISSUE TITLE
Thin is the same weight as Regular (static fonts)

### ISSUE THREAD

**Issue by svipas** [cyrealtype/Inconsolata#71]
Hello, @m4rc1e, thanks a lot for new 3.100 update!

As I understand new Thin weight was added together with this update, but what I found out is that it's actually the same weight as Regular.

### Regular
<img width="605" alt="Screenshot 2022-05-03 at 08 45 55 AM" src="https://user-images.githubusercontent.com/10441177/166409326-ae3898c9-f1b8-46ee-9149-b89932193f77.png">

### Thin
<img width="618" alt="Screenshot 2022-05-03 at 08 48 02 AM" src="https://user-images.githubusercontent.com/10441177/166409476-0472bf32-9ecd-416c-b229-1ce6068f256b.png">

Just wanted to let you know, everything else seems good.

**Comment by m4rc1e** [comment]
Which version of OS X and font book are you running?

On 12.0.1, it looks fine:

<img width="999" alt="Screenshot 2022-05-03 at 08 35 05" src="https://user-images.githubusercontent.com/7525512/166418420-a1e54b4b-ca45-4d9f-b48c-c38b8eee0cbf.png">

<img width="999" alt="Screenshot 2022-05-03 at 08 35 13" src="https://user-images.githubusercontent.com/7525512/166418431-69d6be97-d1f3-4103-9ffc-226aeb58f4a1.png">

**Comment by svipas** [comment]
macOS Monterey (12.3.1 (21E258))
Font book: Version 10.0 (404)

I checked TTF & OTF and they have same issue, Regular weight == Thin weight.

But just to make sure, I installed variable font (`Inconsolata[wdth,wght].ttf`) and turns out that issue doesn't exist for variable font, it only exists for `otf` and `ttf`. I didn't test `webfonts` so maybe there's this problem as well.

**Comment by m4rc1e** [comment]
Ok cool thank you!

I'll inspect the static fonts.

**Comment by svipas** [comment]
Thank you very much @m4rc1e!

**Comment by m4rc1e** [comment]
I've figured out what's happening.

The version we currently serve on [Google fonts](https://fonts.google.com/specimen/Inconsolata?query=inconsolata) doesn't have Thin styles. The family's designspace range is 200-900 so generating a Thin (100) is outside of this range. I'll remove the Thin instances so we've got ExtraLight-Black like we had before.
