### ISSUE TITLE
Cramped equals sign

### ISSUE THREAD

**Issue by redoPop** [cyrealtype/Inconsolata#8]
There seems to be slightly less space between the horizontal bars of the equals sign (`=`) compared with previous versions of the font.

I'm finding that the reduced gap hurts legibility.

**Comment by alexeiva** [comment]
I agree. I am happy to revert to original spacing here. 

Before. Top — legacy. Bottom — v.2.001
<img width="348" alt="screen shot 2017-04-07 at 12 43 21 pm" src="https://cloud.githubusercontent.com/assets/16634089/24795269/73e19390-1b91-11e7-841e-d2a10d2996b4.png">

After. v. 2.002
<img width="295" alt="screen shot 2017-04-07 at 12 46 28 pm" src="https://cloud.githubusercontent.com/assets/16634089/24795270/74ed2e5c-1b91-11e7-8216-30dfe6c8f3be.png">

@m4rc1e can you push this
